# Generated by Django 2.2 on 2022-04-03 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20220403_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_test',
            new_name='status_text',
        ),
    ]
